### ISSUE TITLE
Registration page done

### ISSUE THREAD

**Issue by rayner77** [reynaldicheok/ETI-CA2#10]
Please check the registration page, now im fixing some bugs using pytest on my laptop for my unit tests, the application should run fine, lemme know if any problems faced Thanks

**Comment by ShahrulNizamBR** [comment]
Doubts
- I ran pytest and a sign up page appears, later, it opens another sign up page tab?

**Comment by rayner77** [comment]
Hi sharul, the issue seems to be because of chrome versioning with selenium. Thus, i  have used firefox for the pytest to run with selenium, i  have ran the test cases on my laptop and all 3 test cases have passed. Please review again and let me know if any problems faced. Thankss
__________________________________________________________________________________________________________
test_signup.py ...                                                                                                                           [100%] 

----------- coverage: platform win32, python 3.6.1-final-0 -----------
Name             Stmts   Miss  Cover
------------------------------------
test_signup.py      48      0   100%

**Comment by ShahrulNizamBR** [comment]
Other than the issue above, it is fine.
