### ISSUE TITLE
To Do & To Do History Page

### ISSUE THREAD

**Issue by jonaisahhh** [reynaldicheok/ETI-CA2#3]
The To-Do Page should have the following items

- [x] To-Do items filtered to Users. i.e. Only To-Do items created by Owner is shown.
- [x] Addition and deletion of To-Do items auto archived instead of the current manual process.
- [x] All To-Do items to have a timestamp added upon creation automatically by the application.

**Comment by reynaldicheok** [comment]
Base line feature is done, unit testing is done. Assign to QA
