### ISSUE TITLE
New Feature: Allow sign up for new users

### ISSUE THREAD

**Issue by jonaisahhh** [reynaldicheok/ETI-CA2#8]
The User Login Page should allow

- [ ] New Users to Sign Up

**Comment by rayner77** [comment]
Noted, will start when i'm back from overseas

**Comment by jonaisahhh** [comment]
Hi @kazooie20 , is there any updates on this New Feature request?

Thank you

**Comment by ShahrulNizamBR** [comment]
Hi @jonaisahhh, @kazooie20 has already created the feature and has been tested by me. All good to go.
